# Generated by Django 3.1.5 on 2021-01-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_career_careercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='Description',
            new_name='description',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=350)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.servicecategory')),
            ],
        ),
    ]
