# Generated by Django 3.1.5 on 2021-01-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210124_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='location',
            field=models.CharField(default='Sallaghari', max_length=50),
        ),
    ]
