# Generated by Django 3.1.5 on 2021-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ourplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('development_type', models.CharField(max_length=150)),
                ('plan_type', models.CharField(max_length=150)),
            ],
        ),
    ]
